import Head from "next/head";
import { Inter } from "next/font/google";
import text from "../i18n/i18n";
import { useRouter } from "next/router";
import Section from "../components/Section";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { locale } = router;
  return (
    <>
      <Head>
        <title>Xiao Pan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Section>
          <h1>{text[locale].name}</h1>
          <p>{text[locale].introduction}</p>
        </Section>
        <Section className="">
          <h2>Education</h2>
          <ul className="steps">
            <li className="step step-success">
              Liaoning Mechatronics Collage, China
            </li>
            <li className="step step-primary">
              Shenyang Normal University, China
            </li>
          </ul>
        </Section>
        <Section className="">
          <h2>Certifications</h2>
          <ul>
            <li>RHCSA</li>
          </ul>
        </Section>
        <Section className="">
          <h2>Skills</h2>
          <div className="flex w-full bg-base-400">
            <div className="flex flex-col">
              <p className="m-2">Dev</p>
              <ul className="">
                <li>Python</li>
                <li>Golang</li>
                <li>HTML/CSS</li>
                <li>React.js</li>
              </ul>
            </div>
            <div className="divider lg:divider-horizontal"></div>
            <div className="flex flex-col">
              <p className="m-2">Ops</p>
              <ul className="">
                <li>Linux</li>
                <li>Docker</li>
                <li>Kubernetes</li>
                <li>Git</li>
              </ul>
            </div>
          </div>
        </Section>
        <Section className="">
          <h2>Contact Me</h2>
          <p>E-Mail: pan-xiao#live.cn</p>
        </Section>
      </main>
    </>
  );
}
